const jsTokens = require("js-tokens");

console.log(
    Array.from(jsTokens(process.argv[1]), (token) => token.value).join("|")
);

// MARK: Hacks!

/**
 * More hacks!
 * 
 * Hacks...
 * Hacks...
 * Hacks...
 * Hacks...
 * Hacking the mainframe...
 * Hacks...
 * Hacks...
 * Hacks...
 * Hacks...
 * Hacks...
 * Hacks...
 * Hacks...
 */